"""
Inference service.

Exposes a thin FastAPI wrapper around a Hugging Face zero-shot classification
pipeline (DeBERTa-v3-base fine-tuned on NLI-style data). The API layer
(`api/main.py`) posts batches of comments here, and this service returns the
top-ranked sentiment/intent label for each comment.

Endpoints
---------
GET  /health          - liveness/readiness probe used by the API and Docker.
POST /predict         - classify a single comment.
POST /predict_batch   - classify a list of comments in one forward pass.
GET  /metrics         - Prometheus scrape endpoint.

Prometheus metrics
-------------------
inference_predictions_total       - counter of comments scored.
inference_duration_seconds        - histogram of forward-pass latency per call.
inference_batch_size              - histogram of items per call.
inference_model_ready             - gauge: 1 once the model is loaded, else 0.
"""

import asyncio
import logging
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from transformers import pipeline
import torch
from prometheus_client import Counter, Histogram, Gauge, make_asgi_app

# Configure root logger: timestamp + level + logger name + message. The same
# format is used by the API service so logs from both containers align.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("inference")

# Hard cap on accepted comment length. Mirrors the API layer so requests are
# rejected at the edge before any model work is done.
MAX_COMMENT_LENGTH = 4000

# Candidate labels for the zero-shot classifier. Because the pipeline is a
# natural-language-inference model, these are the hypotheses the comment is
# scored against. They are in German to match the language of the input
# comments generated by `generate_comments.ipynb`.
candidate_labels = [
    "sachliche Kritik",                      # factual / constructive criticism
    "Zustimmung",                            # agreement
    "Sarkasmus oder Ironie",                 # sarcasm or irony
    "Off-Topic-Kommentar",                   # off-topic comment
    "Empörung oder Rant",                    # outrage / rant
    "Desinformation oder Verschwörung",      # misinformation or conspiracy
]

# Module-level model state. Populated by the lifespan handler on startup and
# torn down on shutdown. Health endpoints read these to report readiness.
classifier = None      # transformers.Pipeline instance once loaded.
model_ready = False    # True once the pipeline is ready to serve requests.
model_error = None     # Stores the exception message if model loading failed.

# --- Prometheus metrics -----------------------------------------------------
predictions_total = Counter(
    "inference_predictions_total",
    "Total number of comments scored by the model",
)
inference_duration_seconds = Histogram(
    "inference_duration_seconds",
    "Model forward-pass duration per request in seconds",
    # Buckets chosen to span a single-comment call (~50 ms) up to large
    # batches that may take tens of seconds on CPU.
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)
inference_batch_size = Histogram(
    "inference_batch_size",
    "Number of comments per model call",
    buckets=[1, 2, 4, 8, 16],
)
model_ready_gauge = Gauge(
    "inference_model_ready",
    "1 when the model is loaded and serving, 0 otherwise",
)


@asynccontextmanager
async def lifespan(app):
    """FastAPI lifespan handler: load the model on startup, free it on shutdown.

    Loading is dispatched to a thread executor so the event loop is not
    blocked while the transformers pipeline downloads weights and warms up.
    """
    global classifier, model_ready, model_error
    logger.info("loading model...")
    try:
        # Use GPU (cuda:0) when available, otherwise fall back to CPU.
        device = 0 if torch.cuda.is_available() else "cpu"
        loop = asyncio.get_running_loop()
        # run_in_executor offloads the synchronous `pipeline(...)` call to a
        # worker thread so the async event loop stays responsive.
        classifier = await loop.run_in_executor(
            None,
            lambda: pipeline(
                "zero-shot-classification",
                model="MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli",
                device=device,
            ),
        )
        model_ready = True
        model_ready_gauge.set(1)
        logger.info("model ready")
    except Exception as e:
        # Record the failure so /health can report 503 with a useful detail.
        model_error = str(e)
        logger.error("model loading failed: %s", e)
    yield
    # Shutdown: flip state back so in-flight requests stop using the model.
    model_ready = False
    model_ready_gauge.set(0)
    classifier = None


app = FastAPI(lifespan=lifespan)

# Mount the Prometheus ASGI app under /metrics so the scrape target is
# `http://inference:8001/metrics`.
metrics_app = make_asgi_app()
app.mount("/metrics", metrics_app)


# --- Request / response schemas --------------------------------------------
class PredictRequest(BaseModel):
    comment: str = Field(min_length=1, max_length=MAX_COMMENT_LENGTH)


class PredictResponse(BaseModel):
    label: str
    score: float


class PredictBatchRequest(BaseModel):
    # At least one comment is required; upper bound is enforced implicitly by
    # the API layer's BATCH_SIZE before it reaches this endpoint.
    comments: list[str] = Field(min_length=1)


class PredictBatchResponse(BaseModel):
    results: list[PredictResponse]


def _top_label(output):
    # The zero-shot pipeline returns labels/scores sorted by descending score.
    # We round the score to 2 decimals for compact downstream storage in Redis.
    return PredictResponse(label=output["labels"][0], score=round(float(output["scores"][0]), 2))


@app.get("/health")
def health():
    """Readiness probe.

    Returns 503 with the captured error if model loading failed, 503 with
    "loading" while the model is still warming up, and 200 once ready.
    """
    if model_error:
        return JSONResponse(status_code=503, content={"status": "error", "detail": model_error})
    if not model_ready:
        return JSONResponse(status_code=503, content={"status": "loading"})
    return {"status": "ok"}


@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    """Classify a single comment."""
    if not model_ready:
        return JSONResponse(status_code=503, content={"status": "loading"})
    t0 = time.time()
    output = classifier(req.comment, candidate_labels)
    inference_duration_seconds.observe(time.time() - t0)
    inference_batch_size.observe(1)
    predictions_total.inc()
    return _top_label(output)


@app.post("/predict_batch", response_model=PredictBatchResponse)
def predict_batch(req: PredictBatchRequest):
    """Classify a batch of comments in a single forward pass.

    The API layer calls this endpoint with up to BATCH_SIZE comments at a
    time so the GPU/CPU is utilized more efficiently than one-by-one calls.
    """
    if not model_ready:
        return JSONResponse(status_code=503, content={"status": "loading"})
    t0 = time.time()
    # The pipeline accepts a list of strings and returns a list of dicts in
    # the same order as the input.
    outputs = classifier(req.comments, candidate_labels)
    inference_duration_seconds.observe(time.time() - t0)
    inference_batch_size.observe(len(req.comments))
    predictions_total.inc(len(req.comments))
    return PredictBatchResponse(results=[_top_label(o) for o in outputs])
